# Generated by Django 4.2 on 2025-09-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_layout'),
        ('garpix_page', '0025_remove_basecomponent_anchor_link_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepage',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='app.layout', verbose_name='Раскладка'),
        ),
    ]
