# Generated by Django 4.2 on 2025-09-26 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import polymorphic_tree.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_page', '0027_alter_basecomponent_id_alter_basepage_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormComponent',
            fields=[
                ('basecomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basecomponent')),
                ('form_title', models.CharField(max_length=255, verbose_name='Заголовок формы')),
                ('form_description', models.TextField(blank=True, verbose_name='Описание формы')),
                ('submit_text', models.CharField(default='Отправить', max_length=100, verbose_name='Текст кнопки отправки')),
                ('success_message', models.TextField(default='Форма успешно отправлена!', verbose_name='Сообщение об успехе')),
                ('form_config', models.JSONField(default=dict, help_text='JSON конфигурация полей, созданных в конструкторе', verbose_name='Конфигурация полей формы')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Email уведомления')),
                ('notification_emails', models.TextField(blank=True, help_text='Список email через запятую', verbose_name='Email для уведомлений')),
                ('save_submissions', models.BooleanField(default=True, verbose_name='Сохранять отправки')),
            ],
            options={
                'verbose_name': 'Форма | Form',
                'verbose_name_plural': 'Формы | Forms',
            },
            bases=('garpix_page.basecomponent',),
        ),
        migrations.CreateModel(
            name='FormEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название события')),
                ('event_type', models.CharField(choices=[('email', 'Отправка email'), ('webhook', 'Webhook'), ('database', 'Сохранение в БД'), ('notification', 'Уведомление'), ('redirect', 'Перенаправление'), ('custom', 'Пользовательский код')], max_length=50, verbose_name='Тип события')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок выполнения')),
                ('config', models.JSONField(default=dict, verbose_name='Конфигурация события')),
                ('conditions', models.JSONField(default=list, verbose_name='Условия выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='garpix_page.formcomponent', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Событие формы | Form Event',
                'verbose_name_plural': 'События форм | Form Events',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='draft_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_versions', to='garpix_page.basecomponent', verbose_name='Оригинальный компонент для черновика'),
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='draft_parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_children', to='garpix_page.basepage', verbose_name='Оригинальная страница для черновика'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='seotemplate',
            name='model_rule_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_data', models.JSONField(verbose_name='Данные отправки')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_page.formcomponent', verbose_name='Форма')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отправка формы | Form Submission',
                'verbose_name_plural': 'Отправки форм | Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('skipped', 'Пропущено')], max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Время выполнения (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='garpix_page.formevent', verbose_name='Событие')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='garpix_page.formsubmission', verbose_name='Отправка')),
            ],
            options={
                'verbose_name': 'Лог события | Event Log',
                'verbose_name_plural': 'Логи событий | Event Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
