# Generated by Django 4.2 on 2025-09-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0028_formcomponent_formevent_basecomponent_draft_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecomponent',
            name='draft_of',
        ),
        migrations.RemoveField(
            model_name='basecomponent',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='basepage',
            name='draft_parent',
        ),
        migrations.RemoveField(
            model_name='basepage',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='basecomponent',
            name='draft_data',
            field=models.JSONField(blank=True, help_text='JSON с данными черновика компонента', null=True, verbose_name='Данные черновика'),
        ),
        migrations.AddField(
            model_name='basepage',
            name='draft_data',
            field=models.JSONField(blank=True, help_text='JSON с данными черновика страницы и компонентов', null=True, verbose_name='Данные черновика'),
        ),
    ]
