# Generated by Django 4.2 on 2025-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0029_remove_basecomponent_draft_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcomponent',
            name='form_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Описание формы'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='form_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание формы'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='form_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание формы'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='form_description_zh_hans',
            field=models.TextField(blank=True, null=True, verbose_name='Описание формы'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='form_title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='form_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='form_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='form_title_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок формы'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='submit_text_de',
            field=models.CharField(default='Отправить', max_length=100, null=True, verbose_name='Текст кнопки отправки'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='submit_text_en',
            field=models.CharField(default='Отправить', max_length=100, null=True, verbose_name='Текст кнопки отправки'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='submit_text_ru',
            field=models.CharField(default='Отправить', max_length=100, null=True, verbose_name='Текст кнопки отправки'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='submit_text_zh_hans',
            field=models.CharField(default='Отправить', max_length=100, null=True, verbose_name='Текст кнопки отправки'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='success_message_de',
            field=models.TextField(default='Форма успешно отправлена!', null=True, verbose_name='Сообщение об успехе'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='success_message_en',
            field=models.TextField(default='Форма успешно отправлена!', null=True, verbose_name='Сообщение об успехе'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='success_message_ru',
            field=models.TextField(default='Форма успешно отправлена!', null=True, verbose_name='Сообщение об успехе'),
        ),
        migrations.AddField(
            model_name='formcomponent',
            name='success_message_zh_hans',
            field=models.TextField(default='Форма успешно отправлена!', null=True, verbose_name='Сообщение об успехе'),
        ),
    ]
