# Generated by Django 4.2 on 2025-09-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221020_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(help_text='Уникальный код раскладки (slug)', max_length=100, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Раскладка',
                'verbose_name_plural': 'Раскладки',
                'ordering': ('name',),
            },
        ),
    ]
