# Generated by Django 4.2 on 2025-09-28 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0030_formcomponent_form_description_de_and_more'),
        ('app', '0011_cart_cartitem_cartpage_catalogpage_checkoutpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_page.basepage')),
            ],
            options={
                'verbose_name': 'Превью',
                'verbose_name_plural': 'Превью',
                'ordering': ('-created_at',),
            },
            bases=('garpix_page.basepage',),
        ),
    ]
