# Generated by Django 4.2 on 2025-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_admin_lock', '0002_alter_databasepagelockmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasepagelockmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
